export const NAME_OR_PASSWORD_IS_REQUIRED = "name_or_password_is_required"
export const NAME_IS_ALREADY_EXISTS = "name_is_already_exists"
export const NAME_IS_NOT_EXISTS = "name_is_not_exists"
export const PASSWORD_IS_INCORRECT = "password_is_incorrect"
export const UNAUTHORIZATION = "unauthorization"
export const OPERATION_IS_NOT_ALLOWED = "operation_is_not_allowed"
